#ifndef _OPEN_LTFS_CONST_H
#define _OPEN_LTFS_CONST_H

#define OPEN_LTFS_PERSISTENT_DATA_DIRECTORY "/var/lib/OpenLTFS"
#define OPEN_LTFS_TEMPORARY_DATA_DIRECTORY "/var/run/OpenLTFS"
#define OPEN_LTFS_SERVER_LOCK "/var/lock/OpenLTFS.lock"

#define OPEN_LTFS_RECV_SOCKET_FILE OPEN_LTFS_TEMPORARY_DATA_DIRECTORY "/receiver"
#define OPEN_LTFS_RESP_SOCKET_FILE OPEN_LTFS_TEMPORARY_DATA_DIRECTORY "/responder"



#endif /* _OPEN_LTFS_CONST_H */
