RELPATH = ../..

LIB_SRC_FILES := Server.cc
LIB_SRC_FILES += SubServer.cc
LIB_SRC_FILES += Receiver.cc
LIB_SRC_FILES += Responder.cc
LIB_SRC_FILES += MessageParser.cc
LIB_SRC_FILES += FileOperation.cc
LIB_SRC_FILES += Migration.cc
LIB_SRC_FILES += SelRecall.cc
LIB_SRC_FILES += InfoFiles.cc

CLEANUP_FILES := ltfsdmd
BINARY := ltfsdmd
POSTTARGET :=

include $(RELPATH)/definitions.mk
