RELPATH = ../../../..

LDFLAGS := -lprotobuf -lpthread -lsqlite3 -lconnector -latomic

ARC_SRC_FILES := Action.cc
ARC_SRC_FILES += Cartridge.cc
ARC_SRC_FILES += Drive.cc
ARC_SRC_FILES += Identifier.cc
ARC_SRC_FILES += InternalError.cc
ARC_SRC_FILES += Inventory.cc
ARC_SRC_FILES += Login.cc
ARC_SRC_FILES += LTFSAdminBase.cc
ARC_SRC_FILES += LTFSAdminLog.cc
ARC_SRC_FILES += LTFSAdminMessage.cc
ARC_SRC_FILES += LTFSAdminSession.cc
ARC_SRC_FILES += LTFSNode.cc
ARC_SRC_FILES += LTFSObject.cc
ARC_SRC_FILES += LTFSRequestMessage.cc
ARC_SRC_FILES += LTFSResponseMessage.cc
ARC_SRC_FILES += RequestError.cc
ARC_SRC_FILES += Result.cc
ARC_SRC_FILES += SessionError.cc
ARC_SRC_FILES += XMLError.cc

CLEANUP_FILES :=
BINARY :=
POSTTARGET :=

include $(RELPATH)/definitions.mk
