RELPATH = ../../..

LDFLAGS := -ldm
SHAREDLIB := lib$(notdir $(CURDIR))connector.so

ARC_SRC_FILES :=
CLEANUP_FILES := $(SHAREDLIB)
BINARY := $(SHAREDLIB)
POSTTARGET :=

ARCHIVES :=

include $(RELPATH)/definitions.mk
