#!/bin/bash

MAJOR=0
MINOR=0
BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
COMMIT_TIME=$(date +"%FT%H.%M.%S")
COMMIT_COUNT=$(git rev-list --count HEAD)

VERSION="${MAJOR}.${MINOR}.${COMMIT_COUNT}-${BRANCH_NAME}.${COMMIT_TIME}"
echo ${VERSION} > .version

echo "#pragma once" > "$(git rev-parse --show-toplevel)"/src/common/Version.h
echo "#define LTFSDM_VERSION \"${VERSION}\"" >> "$(git rev-parse --show-toplevel)"/src/common/Version.h

git add -f "$(git rev-parse --show-toplevel)"/src/common/Version.h
