RELPATH = ../../..

SHAREDLIB := lib$(notdir $(CURDIR))connector.so

SO_SRC_FILES := Connector.cc
CLEANUP_FILES := $(SHAREDLIB)
BINARY := $(SHAREDLIB)
POSTTARGET :=

ARCHIVES :=

include $(RELPATH)/definitions.mk
