RELPATH = ../../..

SHAREDLIB := lib$(notdir $(CURDIR))connector.so

LIB_SRC_FILES :=
CLEANUP_FILES := $(SHAREDLIB)
BINARY := $(SHAREDLIB)
POSTTARGET :=

ARCHIVES :=

include $(RELPATH)/definitions.mk
