RELPATH = ../../..

LDFLAGS := -lprotobuf -lpthread -lsqlite3 -lconnector -latomic

ARC_SRC_FILES := LEControl.cc
ARC_SRC_FILES += StatusConv.cc

CLEANUP_FILES :=
BINARY :=
POSTTARGET :=

include $(RELPATH)/definitions.mk
