RELPATH = ../..

LIB_SRC_FILES := Start.cc Stop.cc Migration.cc Recall.cc Help.cc InfoRequests.cc InfoFiles.cc
BIN_SRC_FILES := ltfsdm.cc
CLEANUP_FILES := ltfsdm
BINARY := ltfsdm
POSTTARGET :=

include $(RELPATH)/definitions.mk
